### ISSUE TITLE
RuntimeError: Input type (float) and bias type (struct c10::Half) should be the same

### ISSUE THREAD

**Issue by loichau1997** [mrzaizai2k/License-Plate-Recognition-YOLOv7-and-CNN#5]
I got this error when trying to run the code 

Fusing layers... 
RepConv.fuse_repvgg_block
RepConv.fuse_repvgg_block
RepConv.fuse_repvgg_block
IDetect.fuse
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\research\object_detection\License-Plate-Recognition-YOLOv7-and-CNN\main_image.py", line 29, in <module>
    pred, LP_detected_img = detect(model_LP, source_img, device, imgsz=640)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\research\object_detection\License-Plate-Recognition-YOLOv7-and-CNN\detect.py", line 54, in detect
    pred = model(img, augment=augment)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\research\object_detection\License-Plate-Recognition-YOLOv7-and-CNN\models\yolo.py", line 599, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\research\object_detection\License-Plate-Recognition-YOLOv7-and-CNN\models\yolo.py", line 625, in forward_once
    x = m(x)  # run
        ^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\research\object_detection\License-Plate-Recognition-YOLOv7-and-CNN\models\common.py", line 111, in fuseforward
    return self.act(self.conv(x))
                    ^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Input type (float) and bias type (struct c10::Half) should be the same

**Comment by mrzaizai2k** [comment]
RuntimeError: Input type (float) and bias type (struct c10::Half) should be
the same

I guess you have to convert to the same data type. Check you image

**Comment by loichau1997** [comment]
I actually use the test image without touching anything 

```
image_path = 'data/test/images/clip3_new_0.jpg'
CHAR_CLASSIFICATION_WEIGHTS = './src/weights/weight.h5'
LP_weights = 'LP_detect_yolov7_500img.pt'
```

**Comment by chetan1836** [comment]
I have the same error, any solutions.

**Comment by MinhMISIS** [comment]
you can delete/comment line 35 ( model.half()  # to FP16 ) in detect.py

**Comment by guerrarj** [comment]
> you can delete/comment line 35 ( model.half() # to FP16 ) in detect.py

It actually solved for me. Thank you.
Can you please briefly explain what was happening ?

**Comment by mrzaizai2k** [comment]
Ah I guess because our hardware are different.

**Comment by MinhMISIS** [comment]
> > you can delete/comment line 35 ( model.half() # to FP16 ) in detect.py
> 
> It actually solved for me. Thank you. Can you please briefly explain what was happening ?

it's just data type difference between the model and the input data. If you dont delete that line of code, the model will have the format c10::half (a data type that calculates on the cuda kernel) and input data is float (calculates on cpu). that's what i understand
