### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by thanhlong143** [mrzaizai2k/License-Plate-Recognition-YOLOv7-and-CNN#9]
I got this error when running main_video.py

Traceback (most recent call last):
  File "\License-Plate-Recognition-YOLOv7-and-CNN-main\main_video.py", line 37, in <module>
    pred, LP_detected_img = detect(model_LP, source_img, device, imgsz=640)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\License-Plate-Recognition-YOLOv7-and-CNN-main\detect.py", line 78, in detect
    return final_pred[0].to(device='cpu').detach().numpy(), imgsz
           ~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by mrzaizai2k** [comment]
List out of range is bc your list is empty but u want to make a loop or read sth inside. The reason why your list is empty is mainly because your model cannot catch any license plate or you didnt input the picture so please check the picture or check the output of the model if they return any recognized object
